package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxAdmin;
import org.linlinjava.ax.db.domain.AxAdminExample;

public interface AxAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    long countByExample(AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int deleteByExample(AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int insert(AxAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int insertSelective(AxAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    AxAdmin selectOneByExample(AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    AxAdmin selectOneByExampleSelective(@Param("example") AxAdminExample example, @Param("selective") AxAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    List<AxAdmin> selectByExampleSelective(@Param("example") AxAdminExample example, @Param("selective") AxAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    List<AxAdmin> selectByExample(AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    AxAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    AxAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    AxAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxAdmin record, @Param("example") AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxAdmin record, @Param("example") AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}