package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxAd;
import org.linlinjava.ax.db.domain.AxAdExample;

public interface AxAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    long countByExample(AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int deleteByExample(AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int insert(AxAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int insertSelective(AxAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    AxAd selectOneByExample(AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    AxAd selectOneByExampleSelective(@Param("example") AxAdExample example, @Param("selective") AxAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    List<AxAd> selectByExampleSelective(@Param("example") AxAdExample example, @Param("selective") AxAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    List<AxAd> selectByExample(AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    AxAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    AxAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    AxAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxAd record, @Param("example") AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxAd record, @Param("example") AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}