package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxAddress;
import org.linlinjava.ax.db.domain.AxAddressExample;

public interface AxAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    long countByExample(AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int deleteByExample(AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int insert(AxAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int insertSelective(AxAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    AxAddress selectOneByExample(AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    AxAddress selectOneByExampleSelective(@Param("example") AxAddressExample example, @Param("selective") AxAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    List<AxAddress> selectByExampleSelective(@Param("example") AxAddressExample example, @Param("selective") AxAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    List<AxAddress> selectByExample(AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    AxAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    AxAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    AxAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxAddress record, @Param("example") AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxAddress record, @Param("example") AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}