package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxBrand;
import org.linlinjava.ax.db.domain.AxBrandExample;

public interface AxBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    long countByExample(AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int deleteByExample(AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int insert(AxBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int insertSelective(AxBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    AxBrand selectOneByExample(AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    AxBrand selectOneByExampleSelective(@Param("example") AxBrandExample example, @Param("selective") AxBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    List<AxBrand> selectByExampleSelective(@Param("example") AxBrandExample example, @Param("selective") AxBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    List<AxBrand> selectByExample(AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    AxBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    AxBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    AxBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxBrand record, @Param("example") AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxBrand record, @Param("example") AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}