package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxCategory;
import org.linlinjava.ax.db.domain.AxCategoryExample;

public interface AxCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    long countByExample(AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int deleteByExample(AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int insert(AxCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int insertSelective(AxCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    AxCategory selectOneByExample(AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    AxCategory selectOneByExampleSelective(@Param("example") AxCategoryExample example, @Param("selective") AxCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    List<AxCategory> selectByExampleSelective(@Param("example") AxCategoryExample example, @Param("selective") AxCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    List<AxCategory> selectByExample(AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    AxCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    AxCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    AxCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxCategory record, @Param("example") AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxCategory record, @Param("example") AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}