package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxCart;
import org.linlinjava.ax.db.domain.AxCartExample;

public interface AxCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    long countByExample(AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int deleteByExample(AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int insert(AxCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int insertSelective(AxCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    AxCart selectOneByExample(AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    AxCart selectOneByExampleSelective(@Param("example") AxCartExample example, @Param("selective") AxCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    List<AxCart> selectByExampleSelective(@Param("example") AxCartExample example, @Param("selective") AxCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    List<AxCart> selectByExample(AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    AxCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    AxCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    AxCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxCart record, @Param("example") AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxCart record, @Param("example") AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}