package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxCouponUser;
import org.linlinjava.ax.db.domain.AxCouponUserExample;

public interface AxCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int insert(AxCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(AxCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    AxCouponUser selectOneByExample(AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    AxCouponUser selectOneByExampleSelective(@Param("example") AxCouponUserExample example, @Param("selective") AxCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    List<AxCouponUser> selectByExampleSelective(@Param("example") AxCouponUserExample example, @Param("selective") AxCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    List<AxCouponUser> selectByExample(AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    AxCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    AxCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    AxCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxCouponUser record, @Param("example") AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxCouponUser record, @Param("example") AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}