package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxCoupon;
import org.linlinjava.ax.db.domain.AxCouponExample;

public interface AxCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    long countByExample(AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int insert(AxCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int insertSelective(AxCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    AxCoupon selectOneByExample(AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    AxCoupon selectOneByExampleSelective(@Param("example") AxCouponExample example, @Param("selective") AxCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    List<AxCoupon> selectByExampleSelective(@Param("example") AxCouponExample example, @Param("selective") AxCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    List<AxCoupon> selectByExample(AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    AxCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    AxCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    AxCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxCoupon record, @Param("example") AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxCoupon record, @Param("example") AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}