package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxCollect;
import org.linlinjava.ax.db.domain.AxCollectExample;

public interface AxCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    long countByExample(AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int deleteByExample(AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int insert(AxCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int insertSelective(AxCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    AxCollect selectOneByExample(AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    AxCollect selectOneByExampleSelective(@Param("example") AxCollectExample example, @Param("selective") AxCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    List<AxCollect> selectByExampleSelective(@Param("example") AxCollectExample example, @Param("selective") AxCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    List<AxCollect> selectByExample(AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    AxCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    AxCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    AxCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxCollect record, @Param("example") AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxCollect record, @Param("example") AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}