package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxComment;
import org.linlinjava.ax.db.domain.AxCommentExample;

public interface AxCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    long countByExample(AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int deleteByExample(AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int insert(AxComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int insertSelective(AxComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    AxComment selectOneByExample(AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    AxComment selectOneByExampleSelective(@Param("example") AxCommentExample example, @Param("selective") AxComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    List<AxComment> selectByExampleSelective(@Param("example") AxCommentExample example, @Param("selective") AxComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    List<AxComment> selectByExample(AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    AxComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    AxComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    AxComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxComment record, @Param("example") AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxComment record, @Param("example") AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}