package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxFeedback;
import org.linlinjava.ax.db.domain.AxFeedbackExample;

public interface AxFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    long countByExample(AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int insert(AxFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int insertSelective(AxFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    AxFeedback selectOneByExample(AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    AxFeedback selectOneByExampleSelective(@Param("example") AxFeedbackExample example, @Param("selective") AxFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    List<AxFeedback> selectByExampleSelective(@Param("example") AxFeedbackExample example, @Param("selective") AxFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    List<AxFeedback> selectByExample(AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    AxFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    AxFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    AxFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxFeedback record, @Param("example") AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxFeedback record, @Param("example") AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}