package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxFootprint;
import org.linlinjava.ax.db.domain.AxFootprintExample;

public interface AxFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    long countByExample(AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int insert(AxFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int insertSelective(AxFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    AxFootprint selectOneByExample(AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    AxFootprint selectOneByExampleSelective(@Param("example") AxFootprintExample example, @Param("selective") AxFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    List<AxFootprint> selectByExampleSelective(@Param("example") AxFootprintExample example, @Param("selective") AxFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    List<AxFootprint> selectByExample(AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    AxFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    AxFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    AxFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxFootprint record, @Param("example") AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxFootprint record, @Param("example") AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}