package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxGoodsProduct;
import org.linlinjava.ax.db.domain.AxGoodsProductExample;

public interface AxGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    long countByExample(AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int insert(AxGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(AxGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    AxGoodsProduct selectOneByExample(AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    AxGoodsProduct selectOneByExampleSelective(@Param("example") AxGoodsProductExample example, @Param("selective") AxGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    List<AxGoodsProduct> selectByExampleSelective(@Param("example") AxGoodsProductExample example, @Param("selective") AxGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    List<AxGoodsProduct> selectByExample(AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    AxGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    AxGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    AxGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxGoodsProduct record, @Param("example") AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxGoodsProduct record, @Param("example") AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}