package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxGoodsAttribute;
import org.linlinjava.ax.db.domain.AxGoodsAttributeExample;

public interface AxGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int insert(AxGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(AxGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    AxGoodsAttribute selectOneByExample(AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    AxGoodsAttribute selectOneByExampleSelective(@Param("example") AxGoodsAttributeExample example, @Param("selective") AxGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    List<AxGoodsAttribute> selectByExampleSelective(@Param("example") AxGoodsAttributeExample example, @Param("selective") AxGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    List<AxGoodsAttribute> selectByExample(AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    AxGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    AxGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    AxGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxGoodsAttribute record, @Param("example") AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxGoodsAttribute record, @Param("example") AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}