package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxGoods;
import org.linlinjava.ax.db.domain.AxGoodsExample;

public interface AxGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    long countByExample(AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int deleteByExample(AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int insert(AxGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int insertSelective(AxGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    AxGoods selectOneByExample(AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    AxGoods selectOneByExampleSelective(@Param("example") AxGoodsExample example, @Param("selective") AxGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    AxGoods selectOneByExampleWithBLOBs(AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    List<AxGoods> selectByExampleSelective(@Param("example") AxGoodsExample example, @Param("selective") AxGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    List<AxGoods> selectByExampleWithBLOBs(AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    List<AxGoods> selectByExample(AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    AxGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    AxGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    AxGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxGoods record, @Param("example") AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AxGoods record, @Param("example") AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxGoods record, @Param("example") AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AxGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}