package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxGoodsSpecification;
import org.linlinjava.ax.db.domain.AxGoodsSpecificationExample;

public interface AxGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int insert(AxGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(AxGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    AxGoodsSpecification selectOneByExample(AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    AxGoodsSpecification selectOneByExampleSelective(@Param("example") AxGoodsSpecificationExample example, @Param("selective") AxGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    List<AxGoodsSpecification> selectByExampleSelective(@Param("example") AxGoodsSpecificationExample example, @Param("selective") AxGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    List<AxGoodsSpecification> selectByExample(AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    AxGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    AxGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    AxGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxGoodsSpecification record, @Param("example") AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxGoodsSpecification record, @Param("example") AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}