package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxGrouponRules;
import org.linlinjava.ax.db.domain.AxGrouponRulesExample;

public interface AxGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int insert(AxGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(AxGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    AxGrouponRules selectOneByExample(AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    AxGrouponRules selectOneByExampleSelective(@Param("example") AxGrouponRulesExample example, @Param("selective") AxGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    List<AxGrouponRules> selectByExampleSelective(@Param("example") AxGrouponRulesExample example, @Param("selective") AxGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    List<AxGrouponRules> selectByExample(AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    AxGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    AxGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    AxGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxGrouponRules record, @Param("example") AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxGrouponRules record, @Param("example") AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}