package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxIssue;
import org.linlinjava.ax.db.domain.AxIssueExample;

public interface AxIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    long countByExample(AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int deleteByExample(AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int insert(AxIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int insertSelective(AxIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    AxIssue selectOneByExample(AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    AxIssue selectOneByExampleSelective(@Param("example") AxIssueExample example, @Param("selective") AxIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    List<AxIssue> selectByExampleSelective(@Param("example") AxIssueExample example, @Param("selective") AxIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    List<AxIssue> selectByExample(AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    AxIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    AxIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    AxIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxIssue record, @Param("example") AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxIssue record, @Param("example") AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}