package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxOrder;
import org.linlinjava.ax.db.domain.AxOrderExample;

public interface AxOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    long countByExample(AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int deleteByExample(AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int insert(AxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int insertSelective(AxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    AxOrder selectOneByExample(AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    AxOrder selectOneByExampleSelective(@Param("example") AxOrderExample example, @Param("selective") AxOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    List<AxOrder> selectByExampleSelective(@Param("example") AxOrderExample example, @Param("selective") AxOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    List<AxOrder> selectByExample(AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    AxOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    AxOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    AxOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxOrder record, @Param("example") AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxOrder record, @Param("example") AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}