package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxOrderGoods;
import org.linlinjava.ax.db.domain.AxOrderGoodsExample;

public interface AxOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    long countByExample(AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int insert(AxOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(AxOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    AxOrderGoods selectOneByExample(AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    AxOrderGoods selectOneByExampleSelective(@Param("example") AxOrderGoodsExample example, @Param("selective") AxOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    List<AxOrderGoods> selectByExampleSelective(@Param("example") AxOrderGoodsExample example, @Param("selective") AxOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    List<AxOrderGoods> selectByExample(AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    AxOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    AxOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    AxOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxOrderGoods record, @Param("example") AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxOrderGoods record, @Param("example") AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}