package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxRegion;
import org.linlinjava.ax.db.domain.AxRegionExample;

public interface AxRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    long countByExample(AxRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int deleteByExample(AxRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int insert(AxRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int insertSelective(AxRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    AxRegion selectOneByExample(AxRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    AxRegion selectOneByExampleSelective(@Param("example") AxRegionExample example, @Param("selective") AxRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    List<AxRegion> selectByExampleSelective(@Param("example") AxRegionExample example, @Param("selective") AxRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    List<AxRegion> selectByExample(AxRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    AxRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    AxRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxRegion record, @Param("example") AxRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxRegion record, @Param("example") AxRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxRegion record);
}