package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxRole;
import org.linlinjava.ax.db.domain.AxRoleExample;

public interface AxRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    long countByExample(AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int deleteByExample(AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int insert(AxRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int insertSelective(AxRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    AxRole selectOneByExample(AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    AxRole selectOneByExampleSelective(@Param("example") AxRoleExample example, @Param("selective") AxRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    List<AxRole> selectByExampleSelective(@Param("example") AxRoleExample example, @Param("selective") AxRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    List<AxRole> selectByExample(AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    AxRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    AxRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    AxRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxRole record, @Param("example") AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxRole record, @Param("example") AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}