package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxSearchHistory;
import org.linlinjava.ax.db.domain.AxSearchHistoryExample;

public interface AxSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    long countByExample(AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int insert(AxSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int insertSelective(AxSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    AxSearchHistory selectOneByExample(AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    AxSearchHistory selectOneByExampleSelective(@Param("example") AxSearchHistoryExample example, @Param("selective") AxSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    List<AxSearchHistory> selectByExampleSelective(@Param("example") AxSearchHistoryExample example, @Param("selective") AxSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    List<AxSearchHistory> selectByExample(AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    AxSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    AxSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    AxSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxSearchHistory record, @Param("example") AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxSearchHistory record, @Param("example") AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}