package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxStorage;
import org.linlinjava.ax.db.domain.AxStorageExample;

public interface AxStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    long countByExample(AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int deleteByExample(AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int insert(AxStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int insertSelective(AxStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    AxStorage selectOneByExample(AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    AxStorage selectOneByExampleSelective(@Param("example") AxStorageExample example, @Param("selective") AxStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    List<AxStorage> selectByExampleSelective(@Param("example") AxStorageExample example, @Param("selective") AxStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    List<AxStorage> selectByExample(AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    AxStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    AxStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    AxStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxStorage record, @Param("example") AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxStorage record, @Param("example") AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}