package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxSystem;
import org.linlinjava.ax.db.domain.AxSystemExample;

public interface AxSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    long countByExample(AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int deleteByExample(AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int insert(AxSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int insertSelective(AxSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    AxSystem selectOneByExample(AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    AxSystem selectOneByExampleSelective(@Param("example") AxSystemExample example, @Param("selective") AxSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    List<AxSystem> selectByExampleSelective(@Param("example") AxSystemExample example, @Param("selective") AxSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    List<AxSystem> selectByExample(AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    AxSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    AxSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    AxSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxSystem record, @Param("example") AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxSystem record, @Param("example") AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}