package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxTopic;
import org.linlinjava.ax.db.domain.AxTopicExample;

public interface AxTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    long countByExample(AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int deleteByExample(AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int insert(AxTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int insertSelective(AxTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    AxTopic selectOneByExample(AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    AxTopic selectOneByExampleSelective(@Param("example") AxTopicExample example, @Param("selective") AxTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    AxTopic selectOneByExampleWithBLOBs(AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    List<AxTopic> selectByExampleSelective(@Param("example") AxTopicExample example, @Param("selective") AxTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    List<AxTopic> selectByExampleWithBLOBs(AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    List<AxTopic> selectByExample(AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    AxTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    AxTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    AxTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxTopic record, @Param("example") AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AxTopic record, @Param("example") AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxTopic record, @Param("example") AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AxTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}