package org.linlinjava.ax.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.ax.db.domain.AxUserFormid;
import org.linlinjava.ax.db.domain.AxUserFormidExample;

public interface AxUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    long countByExample(AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int insert(AxUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(AxUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    AxUserFormid selectOneByExample(AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    AxUserFormid selectOneByExampleSelective(@Param("example") AxUserFormidExample example, @Param("selective") AxUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    List<AxUserFormid> selectByExampleSelective(@Param("example") AxUserFormidExample example, @Param("selective") AxUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    List<AxUserFormid> selectByExample(AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    AxUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AxUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    AxUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    AxUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AxUserFormid record, @Param("example") AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AxUserFormid record, @Param("example") AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AxUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AxUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AxUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ax_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}